### ISSUE TITLE
Client/cidr specific upstream dns server configuration

### ISSUE THREAD

**Issue by tahngarth** [0xERR0R/blocky#43] opened 2020-05-07 03:22 UTC
Is there a way to set upstream DNS servers for a specific client or cidr address range? Use case is most clients I want going to Opendns, but some I want going to a geo location spoofing dns (mlb blackout workaround).

**Comment by 0xERR0R** [comment] 2020-05-08 20:13
Currently, there is no way to achieve this behavior. Blocky peeks 2 random upstream resolver from resolver list and uses the answer from the fastest one.

**Comment by 0xERR0R** [comment] 2021-04-09 07:04
Duplicate of #81, closing this issue, because #81 contains more details

**Closed by 0xERR0R** 2021-04-09 07:04 UTC
Labels: duplicate, question
