### ISSUE TITLE
Split DoH port configuration from other HTTP(S)

### ISSUE THREAD

**Issue by ThinkChaos** [0xERR0R/blocky#1416] opened 2024-03-27 17:08 UTC
Allow setting up DoH separately from other HTTP endpoints. That way metrics, API, etc. can listen, for instance, on localhost only and DoH on all interfaces.  
That could make setups with all API access being authenticated (accessed  from localhost, through a reverse proxy, VPN, etc.) much easier at little cost for blocky.

This was mentioned in #1408.

**Comment by gspannu** [comment] 2024-03-27 20:55
_As a side issue..._

While making DoH queries, Blocky correctly identifies the _clientIP_ and _clientName_. 
So, when making a DoH query using `https://myblockyaddress.com/dns-query/client0001 ` the clientIP is listed as the actual physical **IPaddress**, and the clientName is listed as **client0001** (as provided in the url)
Works exactly as expected. 👍 

However, making the same DNS query using DoT, Blocky correctly identifies the _clientIP_ but **not** the _clientName_.
So, when making a DoT query using `tls://client0001.myblockyaddress.com` the clientIP is listed as the actual physical **IPaddress**, but the clientName is listed as the public DNS name of the IP address rather than **client0001**  (as provided in the url) 😕

Is this expected behaviour or should DoT queries also show the client name in the url.

---

Actual example from Blocky Query Logs:
If I make DoH or DoT queries from 100.235.175.103 to my Blocky instance using above example:
DoH query: shows `clientIP as 100.235.175.103` and `clientName as client0001`
DoT query: shows `clientIP as 100.235.175.103` and `clientName as no-rdns.stratagem.host`

**Comment by ThinkChaos** [comment] 2024-03-28 00:15
@gspannu you need add `id-` prefix to the subdomain, see [Resolving client name from URL/Host](https://0xerr0r.github.io/blocky/v0.23/configuration/#resolving-client-name-from-urlhost).  
Please make a new issue/discussion in the future :)

**Comment by gspannu** [comment] 2024-03-28 01:09
> @gspannu you need add `id-` prefix to the subdomain, see [Resolving client name from URL/Host](https://0xerr0r.github.io/blocky/v0.23/configuration/#resolving-client-name-from-urlhost). Please make a new issue/discussion in the future :)

You are a star 🌟... 
... and message to self - RTFM !!!

**Comment by kwitsch** [comment] 2024-03-31 21:39
Duplicate of issue #1206

**Closed** 2024-03-31 21:39 UTC
